from_latest_tag = false
ignore_merge_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks.pre-push]
path = "hooks/pre-push.sh"

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "paystack_sdk"
owner = "irabeny89"
authors = [
  { signature = "Ernest Irabor", username = "Irabeny" }
]

[bump_profiles]

[packages]