name: CI

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  # 1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Format And Lint
        run: bun run check

      - name: Test Code
        run: bun test

  # 2
  build-and-deploy-docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean The Package
        run: rm -f ./tsconfig.json; rm -rf ./docs

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      
      - name: Install Dependencies
        run: |
          bun add next react react-dom
          bun install --global bun-doc

      - name: Build Documentation Page
        run: |
          bun-doc build
          bunx next build && bunx next export
          mv ./out ./docs

      - name: Deploy Documentation Page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs

  # 3
  commit-and-changelog:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Conventional Commit Check
        uses: cocogitto/cocogitto-action@v3

      - name: Semver Release
        uses: cocogitto/cocogitto-action@v3
        id: release
        with:
          release: true
          git-user: 'irabeny89'
          git-user-email: 'irabeny89@gmail.com'

      # The version number is accessible as a github action output
      - name: Print Version
        run: "echo '${{ steps.release.outputs.version }}'"

      - name: Upload Github Release
        id: gh-release
        uses: softprops/action-gh-release@v2
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
        
  # 4
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Publish To JSR
        run: bun run publish