name: CI

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - main

  pull_request: 
    branches: 
      - main

jobs:
  # 1
  test_and_publish:
    name: Run Tests And Publish To JSR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Format And Lint
        run: bun run check

      - name: Test Code
        run: bun test

      - name: Bump Version
        run: bun bump-version.ts

      - name: Publish To JSR
        run: bunx jsr publish --allow-dirty

  # 2
  changelog_release:
    name: Check Commit, Generate Changelog and Upload Release On Github
    needs: test_and_publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # pick the pr HEAD instead of the merge commit
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Conventional Commit Check
        uses: cocogitto/cocogitto-action@v3

      - name: Semver Release
        uses: cocogitto/cocogitto-action@v3
        id: release
        with:
          release: true
          git-user: 'irabeny89'
          git-user-email: 'irabeny89@gmail.com'
          
      # The version number is accessible as a github action output
      - name: Print Version
        run: "echo '${{ steps.release.outputs.version }}'"

      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md  
          
      - name: Upload Github Release
        id: gh-release
        uses: softprops/action-gh-release@v2
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}