name: CI

env:
  USER: ${{ github.actor }}
  EMAIL: "${{ github.actor }}+github-actions@users.noreply.github.com"

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Initialize Git Config
        run: |
          git config --global user.name "${{ env.USER }}"
          git config --global user.email "${{ env.EMAIL }}"

      - name: Format And Lint
        run: |
          bun run check
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "style: format and lint"
          fi

      - name: Get Next Version
        uses: cocogitto/cocogitto-action@v3
        id: next-version
        with:
          dry-run: true

      - name: Update Version
        run: |
          NEXT_VERSION=${{ steps.next-version.outputs.version }} bun bump-version
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "chore: version bump to ${{ steps.next-version.outputs.version }}"
          fi

      - name: Run Tests On Utils Only
        run: bun test-utils

      - name: Push Committed Changes
        run: |
          if git rev-list --count --left-only @{upstream}...HEAD > /dev/null 2>&1; then
            git push origin main
          fi

      - name: Conventional Commit and Semver Release
        uses: cocogitto/cocogitto-action@v3
        id: release
        with:
          release: true
          git-user: "${{ env.USER }}"
          git-user-email: "${{ env.EMAIL }}"

      - name: Generate Github Release Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload Github Release
        id: gh-release
        uses: softprops/action-gh-release@v2
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}

      - name: Publish To JSR
        run: bunx publish --allow-dirty
